package provideraws

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"testing"
)

// namesAttrsFile is the table of the provider's names.Attr constants.
const namesAttrsFile = "names_attrs_gen.go"

// TestNamesAttrConsts checks namesAttrConsts against names/attr_consts_gen.go
// of the provider checkout, and skips when the checkout is absent. Set
// UPDATE_NAMES_ATTRS=1 to rewrite the table.
func TestNamesAttrConsts(t *testing.T) {
	if testing.Short() {
		t.Skip("needs the provider checkout")
	}
	src := filepath.Join(defaultCacheDir(), "names", "attr_consts_gen.go")
	if _, err := os.Stat(src); err != nil {
		t.Skipf("provider checkout not found at %s", src)
	}
	consts, err := readStringConsts(src)
	if err != nil {
		t.Fatal(err)
	}
	want := renderNamesAttrs(t, consts)

	if os.Getenv("UPDATE_NAMES_ATTRS") != "" {
		if err := os.WriteFile(namesAttrsFile, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(namesAttrsFile)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale; regenerate it with UPDATE_NAMES_ATTRS=1", namesAttrsFile)
	}
}

// readStringConsts returns the string constants a Go file declares.
func readStringConsts(path string) (map[string]string, error) {
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	if err != nil {
		return nil, err
	}
	consts := map[string]string{}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			for i, name := range vs.Names {
				if i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				v, err := strconv.Unquote(lit.Value)
				if err != nil {
					return nil, err
				}
				consts[name.Name] = v
			}
		}
	}
	return consts, nil
}

// renderNamesAttrs returns the source of namesAttrsFile for consts.
func renderNamesAttrs(t *testing.T, consts map[string]string) []byte {
	t.Helper()
	keys := make([]string, 0, len(consts))
	for k := range consts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by TestNamesAttrConsts; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package provideraws\n\n")
	fmt.Fprintf(&b, "// namesAttrConsts maps each attribute name constant of the provider's\n")
	fmt.Fprintf(&b, "// names package (names/attr_consts_gen.go at %s) to the attribute it\n", DefaultProviderRef)
	fmt.Fprintf(&b, "// spells, so a guard such as d.HasChange(names.AttrKMSKeyID) names kms_key_id.\n")
	fmt.Fprintf(&b, "// Regenerate it with UPDATE_NAMES_ATTRS=1 go test -run TestNamesAttrConsts ./internal/provideraws/\n")
	fmt.Fprintf(&b, "var namesAttrConsts = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, consts[k])
	}
	fmt.Fprintf(&b, "}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	return out
}
