name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Format check
        run: test -z "$(gofmt -l .)"

      - name: Test (short)
        run: go test ./... -short -count=1 -v

  test-live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Test (live CFN registry)
        run: go test ./... -count=1 -v
